- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
  with_items: directories
  tags: [petclinic]

- name: download files from s3
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    timeout: 240
    mode: "{{ item.mode }}"
  with_items: files_to_download
  tags: [petclinic]

#- name: tomcat is restarted
#  service: 
#    name: tomcat
#    state: restarted
#  when: result|changed
#  tags: [petclinic]